name: agent_flutter
version: 0.4.0
description: Completely new way to manage state and events.
homepage: https://github.com/iamguid/agent
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  agent_core: ^0.4.0
  provider: ^6.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.1.1
  flutter_test:
    sdk: flutter
