name: agent_flutter
description: Agent is not yet another state management library. It is completely new way to manage state and events.
version: 0.2.5
homepage: https://github.com/iamguid/agent

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  agent_core: ^0.3.0
  provider: ^6.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  flutter_test:
    sdk: flutter