name: agent_flutter
description: Agent is not yet another state management library. It is completely new way to manage state and events.
version: 0.1.2
homepage: https://github.com/iamguid/agent

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  agent_core: ^0.1.2
  provider: ^6.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
