name: agent_core
version: 0.4.0
description: Completely new way to manage state and events.
homepage: https://github.com/iamguid/agent
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'

dev_dependencies:
  lints: ^5.1.1
  test: ^1.16.0
